# Publish all joint states -----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Effort Controllers ---------------------------------------
column_1_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: column_1_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
column_2_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: column_2_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
column_3_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: column_3_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
column_4_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: column_4_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
column_5_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: column_5_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
column_6_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: column_6_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
column_7_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: column_7_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
column_8_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: column_8_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

neck_1_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_1_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
neck_2_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_2_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
neck_3_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_3_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
neck_4_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_4_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
neck_5_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: neck_5_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

left_shoulder_spherical_roll_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_shoulder_spherical_roll_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
left_shoulder_spherical_pitch_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_shoulder_spherical_pitch_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
right_shoulder_spherical_roll_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_shoulder_spherical_roll_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
right_shoulder_spherical_pitch_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_shoulder_spherical_pitch_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

left_forearm_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_forearm_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
right_forearm_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_forearm_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}


left_thigh_spherical_roll_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_thigh_spherical_roll_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
left_thigh_spherical_pitch_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_thigh_spherical_pitch_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
right_thigh_spherical_roll_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_thigh_spherical_roll_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
right_thigh_spherical_pitch_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_thigh_spherical_pitch_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
  

left_wrist_spherical_roll_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_wrist_spherical_roll_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
left_wrist_spherical_pitch_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_wrist_spherical_pitch_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
right_wrist_spherical_roll_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_wrist_spherical_roll_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
right_wrist_spherical_pitch_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_wrist_spherical_pitch_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}

left_wrist_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_wrist_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
right_wrist_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_wrist_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}


left_ankle_spherical_roll_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_ankle_spherical_roll_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
left_ankle_spherical_pitch_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_ankle_spherical_pitch_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
right_ankle_spherical_roll_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_ankle_spherical_roll_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
right_ankle_spherical_pitch_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_ankle_spherical_pitch_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}


left_ankle_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: left_ankle_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}
right_ankle_yaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: right_ankle_yaw_joint
  pid: {p: 10.0, i: 0.0, d: 0.0}










    