<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Constants -->
	<xacro:property name="PI" value="3.1415926535897931"/>
	
	<!-- Golden Ratio -->
	<xacro:property name="PHI" value="1.618033988749"/>
	<xacro:property name="PHI2" value="${PHI*PHI}"/>
	<xacro:property name="PHI3" value="${PHI2*PHI}"/>

	<!-- chest_link Properties -->
	<xacro:property name="chest_link_x" value="0.2"/>
	<xacro:property name="chest_link_y" value="0.3"/>
	<xacro:property name="chest_link_z" value="0.3"/>
	<xacro:property name="chest_link_mass" value="0.1"/>

	<!-- pelvis_link Properties -->
	<xacro:property name="pelvis_link_x" value="0.15816"/>
	<xacro:property name="pelvis_link_y" value="0.28838"/>
	<xacro:property name="pelvis_link_z" value="0.10665"/>
	<xacro:property name="pelvis_link_mass" value="0.1"/>

	<!-- flex Properties-->
    
    <xacro:property name="flex_link_length" value="0.04"/>
    <xacro:property name="flex_delta_length" value="${flex_link_length / PHI2}"/>

    <xacro:property name="flex_link_mass" value="0.01"/>
    <xacro:property name="flex_joint_lim_roll_low" value="-0.1"/>
    <xacro:property name="flex_joint_lim_roll_up" value="0.1"/>
	<xacro:property name="flex_joint_lim_pitch_low" value="-0.1"/>
    <xacro:property name="flex_joint_lim_pitch_up" value="0.1"/>
	<xacro:property name="flex_joint_lim_yaw_low" value="-0.1"/>
    <xacro:property name="flex_joint_lim_yaw_up" value="0.1"/>
    <xacro:property name="flex_joint_effort" value="10000.0"/>
    <xacro:property name="flex_joint_vel" value="0.1"/>
    <!-- define the list of flex links, it has to start with 1 and generate consecutive numbers -->
    <xacro:property name="flex_indexes" value="${[1,2,3,4,5,6,7,8]}" />

	<!-- Arms-->
	
	<xacro:property name="shoulder_link_mass" value="0.05"/>
    <xacro:property name="shoulder_link_radius" value="0.05"/>
    <xacro:property name="shoulder_link_length" value="0.2"/>
	<xacro:property name="shoulder_link_lim_down" value="-0.05"/>
    <xacro:property name="shoulder_link_lim_up" value="0.05"/>
	<xacro:property name="shoulder_max_effort" value="10000.0"/>
	<xacro:property name="shoulder_max_vel" value="3.0"/>

	<xacro:property name="forearm_link_mass" value="0.05"/>
    <xacro:property name="forearm_link_radius" value="0.03"/>
    <xacro:property name="forearm_link_length" value="0.2"/>
	<xacro:property name="forearm_link_lim_down" value="-2.0"/>
    <xacro:property name="forearm_link_lim_up" value="0.05"/>
	<xacro:property name="forearm_max_effort" value="10000.0"/>
	<xacro:property name="forearm_max_vel" value="3.0"/>


	<!-- Legs -->
	<xacro:property name="thigh_link_mass" value="0.1"/>
    <xacro:property name="thigh_link_radius" value="0.05"/>
    <xacro:property name="thigh_link_length" value="0.2"/>
	<xacro:property name="thigh_link_lim_down" value="-0.05"/>
    <xacro:property name="thigh_link_lim_up" value="0.05"/>
	<xacro:property name="thigh_max_effort" value="10000.0"/>
	<xacro:property name="thigh_max_vel" value="3.0"/>

	<xacro:property name="shin_link_mass" value="0.05"/>
    <xacro:property name="shin_link_radius" value="0.03"/>
    <xacro:property name="shin_link_length" value="0.2"/>
	<xacro:property name="shin_link_lim_down" value="0.05"/>
    <xacro:property name="shin_link_lim_up" value="2.0"/>
	<xacro:property name="shin_max_effort" value="10000.0"/>
	<xacro:property name="shin_max_vel" value="3.0"/>

	<!-- Head -->
	
	<xacro:property name="head_link_mass" value="0.05"/>
    <xacro:property name="head_link_r" value="0.1"/>	
	<xacro:property name="flex_neck_indexes" value="${[1,2,3,4,5]}" />

	<!-- Hands -->
		
	<xacro:property name="wrist_link_mass" value="0.01"/>
    <xacro:property name="wrist_link_radius" value="0.05"/>	
	<xacro:property name="wrist_link_length" value="0.01"/>	
	<xacro:property name="wrist_yaw_link_lim_down" value="-0.1"/>
    <xacro:property name="wrist_yaw_link_lim_up" value="0.1"/>	
	<xacro:property name="wrist_yaw_link_max_effort" value="10.0"/>
    <xacro:property name="wrist_yaw_link_max_vel" value="3.0"/>	

		
	<xacro:property name="hand_link_mass" value="0.05"/>
    <xacro:property name="hand_link_r" value="0.05"/>

	<xacro:property name="hand_kp" value="100000.0"/>
	<xacro:property name="hand_kd" value="100000.0"/>
	<xacro:property name="hand_mu1" value="10.0"/>
	<xacro:property name="hand_mu2" value="10.0"/>

	<!-- Foot -->	
	<xacro:property name="ankle_link_mass" value="0.01"/>
    <xacro:property name="ankle_link_radius" value="0.05"/>	
	<xacro:property name="ankle_link_length" value="0.01"/>	
	<xacro:property name="ankle_yaw_link_lim_down" value="-0.1"/>
    <xacro:property name="ankle_yaw_link_lim_up" value="0.1"/>	
	<xacro:property name="ankle_yaw_link_max_effort" value="10000.0"/>
    <xacro:property name="ankle_yaw_link_max_vel" value="3.0"/>

	<xacro:property name="foot_link_mass" value="0.01"/>
    <xacro:property name="foot_link_x" value="0.15"/>
	<xacro:property name="foot_link_y" value="0.1"/>
	<xacro:property name="foot_link_z" value="0.05"/>

	<xacro:property name="foot_kp" value="100000.0"/>
	<xacro:property name="foot_kd" value="100000.0"/>
	<xacro:property name="foot_mu1" value="10.0"/>
	<xacro:property name="foot_mu2" value="10.0"/>
	

	
</robot>
