joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

forward_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - joint1
    - joint2
